LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/dse_netstats-rr.csv'       INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_dse_netstats_rr FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/dse_netstats-messages.csv' INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_dse_netstats_messages FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/iostat-cpu.csv'            INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_iostat_cpu FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/iostat-disk.csv'           INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_iostat_disk FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/mpstat-cpu.csv'            INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_mpstat_cpu FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/mpstat-interrupt.csv'      INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_mpstat_interrupt FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/proxyhistograms.csv'    INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_proxyhistograms FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/tablehistograms.csv'    INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_tablehistograms FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/tablestats.csv'        INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_tablestats FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/tpstats-messages.csv'   INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_tpstats_messages FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/tpstats-pools.csv'      INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_tpstats_pools FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/tpstats-tpcpools.csv'   INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_tpstats_tpcpools FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/ttop-onlycore.csv'      INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_ttop_onlycore FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/ttop-summary.csv'       INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_ttop_summary FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/ttop-detail.csv'        INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_ttop_detail FIELDS TERMINATED BY ',';


LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/log-asyncr.csv'     INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_async FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/log-slowq.csv'      INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_slow FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/log-gc.csv'         INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_gc FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/log-fl_largest.csv' INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_fl_largest FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/log-fl_forcing.csv' INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_fl_forcing FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/log-delsst.csv'     INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_delsst FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '$ABO_BASE_DIR/unload/log-fl_enqueue.csv' INTO TABLE for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_fl_enqueue FIELDS TERMINATED BY ',';

-- truncate commands
TRUNCATE TABLE  for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_slow;
TRUNCATE TABLE  for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_gc;
TRUNCATE TABLE  for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_fl_largest;
TRUNCATE TABLE  for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_fl_forcing;
TRUNCATE TABLE  for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_delsst;
TRUNCATE TABLE  for_grafana.<CUSTOMER_NAME>_<CASE_NUMBER>_<SAMPLE_SET>_fl_enqueue;
